language: node_js
node_js:
- "8.9.4"
script: 
  - yarn format:verify
  - yarn lint
  - yarn test
deploy:
  - provider: azure_web_apps
    verbose: true
    on: feature/database-layer
    site: register-a-food-business-service-dev
  - provider: azure_web_apps
    verbose: true
    on: master
    site: TEST-REGISTER-A-FOOD-BUSINESS-SERVICE