language: node_js
node_js:
- "8.9.4"
git:
   depth: 9999999
before_deploy: "echo 'ready?'"
deploy:
- provider: azure_web_apps
  verbose: true
  on: feature/travis-deploy
  site: register-a-food-business-service-dev