language: node_js
node_js:
- "8.9.4"
git:
   depth: 9999999
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
jobs:
  include:
    - stage: format
      install: true
      script: yarn format:verify
    - stage: lint
      install: true
      script: yarn lint
    - stage: unit test
      install: true
      script: yarn test
before_deploy: "rm -rf node_modules coverage package-lock.json"
deploy:
  - provider: azure_web_apps
    verbose: true
    on: develop
    site: dev-register-a-food-business-service
    skip_cleanup: true
  - provider: azure_web_apps
    verbose: true
    on: develop
    site: dev-register-a-food-business-service
    slot: dev-register-a-food-business-service-double
    skip_cleanup: true
  - provider: azure_web_apps
    verbose: true
    on: develop
    site: test-register-a-food-business-service
    skip_cleanup: true
  - provider: azure_web_apps
    verbose: true
    on: develop
    site: test-register-a-food-business-service
    slot: test-register-a-food-business-service-double
    skip_cleanup: true
  - provider: azure_web_apps
    verbose: true
    on: release
    site: staging-register-a-food-business-service
    skip_cleanup: true
  - provider: azure_web_apps
    verbose: true
    on: master
    site: prod-register-a-food-business-service
    slot: prod-register-a-food-business-service-double
    skip_cleanup: true