# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
# - task: Npm@1
#   inputs:
#     customEndpoint: fsa
- script: echo $NPM_TOKEN
  displayName: 'Echo'

- script: npm install
  displayName: 'Install'

- script: npm test
  displayName: 'Unit tests'


