# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: npm install
  displayName: 'Install'

- script: npm test
  displayName: 'Unit tests'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFile: ./reports/TEST-unit.xml
    testRunTitle: Unit tests

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    connectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure (foodgov): #1046244 ( b894ef5e-e572-42c1-b006-89a03c6539f6 )'
    appType: 'webAppLinux'
    webAppName: 'dev-register-a-food-business-service'
    runtimeStack: 'node|8.9'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*/.zip'


