# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - script: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    displayName: Create .npmrc

  - script: npm -v
    displayName: "Npm version"

  - script: npm install -g yarn@1.6.0
    displayName: "Install yarn"

  - script: yarn format:verify
    displayName: "Format"

  - script: yarn lint
    displayName: "Lint"

  - script: yarn test:unit:ci
    displayName: "Unit tests"

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFile: ./reports/TEST-unit.xml
      testRunTitle: Unit tests
      mergeTestResults: false

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage/lcov-report"

  - script: yarn test:integration
    displayName: "Integration tests"

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFile: ./reports/TEST-integration.xml
      testRunTitle: Integration tests
      mergeTestResults: false

  - script: yarn --production
    displayName: Prune dev dependencies

  - script: rm -rf coverage reports
    displayName: Remove reporting folders

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
