# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: npm install
  displayName: 'Install'

- script: npm format:verify
  displayName: 'Format'

- script: npm lint
  displayName: 'Lint'

- script: npm test
  displayName: 'Unit tests'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFile: ./reports/TEST-unit.xml
    testRunTitle: Unit tests

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1


