require("dotenv").config();

module.exports = {
  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_PASS: process.env.POSTGRES_PASS,
  POSTGRES_HOST: process.env.POSTGRES_HOST,
  POSTGRES_DB: process.env.POSTGRES_DB,
  NOTIFY_KEY: process.env.NOTIFY_KEY,
  NOTIFY_TEMPLATE_ID_FBO: process.env.NOTIFY_TEMPLATE_ID_FBO,
  NOTIFY_TEMPLATE_ID_LC: process.env.NOTIFY_TEMPLATE_ID_LC,
  NOTIFY_TEMPLATE_ID_TEST: process.env.NOTIFY_TEMPLATE_ID_TEST,
  MONGO_CONFIGDB_CONNECTION_STRING: process.env.MONGO_CONFIGDB_CONNECTION_STRING
};
